# Generated by Django 5.1.1 on 2024-09-17 16:02

import examenes.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.UUID('37ff47ce-750e-11ef-99e4-f0038c90f80e'), primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('37ff47cf-750e-11ef-9e85-f0038c90f80e'), primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to=examenes.models.Examen.upload_to)),
            ],
        ),
    ]
