# Generated by Django 5.1.1 on 2024-09-17 16:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9b2f880-750e-11ef-8b8b-f0038c90f80e'), primary_key=True, serialize=False),
        ),
    ]
