# Generated by Django 5.1.1 on 2024-09-17 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0003_alter_categoria_id_alter_examen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='id',
            field=models.UUIDField(default=uuid.UUID('333df1b5-7511-11ef-856d-f0038c90f80e'), primary_key=True, serialize=False),
        ),
    ]
