# Generated by Django 5.1.1 on 2024-09-17 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0004_alter_examen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac3750fb-7511-11ef-83a1-f0038c90f80e'), primary_key=True, serialize=False),
        ),
    ]
