# Generated by Django 5.1.1 on 2024-09-18 12:06

import django.db.models.deletion
import examenes.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0007_alter_examen_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='examen',
            options={'verbose_name': 'Examen', 'verbose_name_plural': 'Examenes'},
        ),
        migrations.AddField(
            model_name='examen',
            name='descripcion',
            field=models.CharField(default=1, max_length=1000, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=100, unique=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='create_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Actualizacion'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='agregado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agregado Por'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='archivo',
            field=models.FileField(upload_to=examenes.models.Examen.upload_to, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='create_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion'),
        ),
    ]
