# Generated by Django 5.1.1 on 2024-09-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0008_alter_categoria_options_alter_examen_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='descripcion',
            field=models.TextField(max_length=1000, verbose_name='Descripción'),
        ),
    ]
