# Generated by Django 5.1.1 on 2024-09-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0009_alter_examen_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
