# Generated by Django 5.1.1 on 2024-09-17 12:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.UUID('168032c7-74f2-11ef-886b-f0038c90f80e'), primary_key=True, serialize=False),
        ),
    ]
