# Generated by Django 5.1.1 on 2024-09-17 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b8a585b0-8e03-4ecf-90f9-7cbdeb4495e5'), primary_key=True, serialize=False),
        ),
    ]
