# Generated by Django 5.1.1 on 2024-09-18 11:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ci',
            field=models.IntegerField(unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='create_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion'),
        ),
    ]
