# Generated by Django 5.1.1 on 2024-09-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_avatar_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, default='no-email.9998153975734bf9aec348f399a95ea9', max_length=254, null=True, unique=True, verbose_name='Correo Electronico'),
        ),
    ]
