# Generated by Django 5.0.9 on 2024-09-18 13:11

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_ci_alter_usuario_create_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.models.generar_nombre, verbose_name='Avatar'),
        ),
    ]
