# Generated by Django 5.0.9 on 2024-09-18 13:19

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, height_field=730, null=True, upload_to=usuarios.models.generar_nombre, verbose_name='Avatar', width_field=730),
        ),
    ]
