# Generated by Django 5.1.1 on 2024-09-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, default='no-email.52e616a79cfa4f7f89ce31884b779033@noemail.com', max_length=254, null=True, unique=True, verbose_name='Correo Electronico'),
        ),
    ]
