# Generated by Django 5.0.9 on 2024-09-18 13:25

import django_resized.forms
import usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[730, 730], upload_to=usuarios.models.generar_nombre, verbose_name='Avatar'),
        ),
    ]
