# Generated by Django 5.1.1 on 2024-09-17 16:02

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('especialidad', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.UUID('3806f5bd-750e-11ef-898c-f0038c90f80e'), primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('institucion', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.UUID('3806f5be-750e-11ef-9b44-f0038c90f80e'), primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
