# Generated by Django 5.0.9 on 2024-09-21 00:26

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100, unique=True, verbose_name='Especialidad')),
                ('create_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Creacion')),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('nombre', models.CharField(max_length=100, verbose_name='Primer Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Primer Apellido')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Número de Teléfono')),
                ('institucion', models.CharField(max_length=100, verbose_name='Institución')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creacion')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion')),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
            },
        ),
    ]
