# Generated by Django 5.1.1 on 2024-09-17 16:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9baa486-750e-11ef-9f89-f0038c90f80e'), primary_key=True, serialize=False),
        ),
    ]
