# Generated by Django 5.1.1 on 2024-09-17 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_alter_especialidad_id_alter_medico_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ba8c857-7635-42a0-a94d-e128d7032a0b'), primary_key=True, serialize=False),
        ),
    ]
