# Generated by Django 5.1.1 on 2024-09-17 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0004_alter_medico_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='especialidad',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f76a199-0df8-4fbe-ae45-645a06d37391'), primary_key=True, serialize=False),
        ),
    ]
