# Generated by Django 5.1.1 on 2024-09-18 11:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0006_alter_medico_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
