# Generated by Django 5.1.1 on 2024-09-18 12:06

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0007_alter_medico_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'Medico', 'verbose_name_plural': 'Medicos'},
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='create_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='especialidad',
            field=models.CharField(max_length=100, unique=True, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Actualizacion'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='agregado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agregado Por'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='create_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.especialidad', verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='institucion',
            field=models.CharField(max_length=100, verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Número de Teléfono'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualizacion'),
        ),
    ]
